[k8s_control_plane]
control-plane ansible_host=YOUR_CONTROL_PLANE_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/kops-capstone

[k8s_workers]
worker1 ansible_host=YOUR_WORKER1_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/kops-capstone
worker2 ansible_host=YOUR_WORKER2_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/kops-capstone
worker3 ansible_host=YOUR_WORKER3_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/kops-capstone

[k8s_cluster:children]
k8s_control_plane
k8s_workers