---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Ensure fail2ban is running
  service:
    name: fail2ban
    state: started
    enabled: true
